config/routes.rb
Rails.application.routes.draw do
  resources :sms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sm.rb
class Sm < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  before_action :set_sm, only: [:show, :edit, :update, :destroy]

  # GET /sms
  # GET /sms.json
  def index
    @sms = Sm.all
  end

  # GET /sms/1
  # GET /sms/1.json
  def show
  end

  # GET /sms/new
  def new
    @sm = Sm.new
  end

  # GET /sms/1/edit
  def edit
  end

  # POST /sms
  # POST /sms.json
  def create
    @sm = Sm.new(sm_params)

    respond_to do |format|
      if @sm.save
        format.html { redirect_to @sm, notice: 'Sm was successfully created.' }
        format.json { render :show, status: :created, location: @sm }
      else
        format.html { render :new }
        format.json { render json: @sm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sms/1
  # PATCH/PUT /sms/1.json
  def update
    respond_to do |format|
      if @sm.update(sm_params)
        format.html { redirect_to @sm, notice: 'Sm was successfully updated.' }
        format.json { render :show, status: :ok, location: @sm }
      else
        format.html { render :edit }
        format.json { render json: @sm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sms/1
  # DELETE /sms/1.json
  def destroy
    @sm.destroy
    respond_to do |format|
      format.html { redirect_to sms_url, notice: 'Sm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sm
      @sm = Sm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sm_params
      params.require(:sm).permit(:body, :from, :received_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codepeepsfeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sms/_form.html.erb
<%= form_for(sm) do |f| %>
  <% if sm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sm.errors.count, "error") %> prohibited this sm from being saved:</h2>

      <ul>
      <% sm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="field">
    <%= f.label :from %>
    <%= f.text_field :from %>
  </div>

  <div class="field">
    <%= f.label :received_at %>
    <%= f.datetime_select :received_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sms/edit.html.erb
<h1>Editing Sm</h1>

<%= render 'form', sm: @sm %>

<%= link_to 'Show', @sm %> |
<%= link_to 'Back', sms_path %>

app/views/sms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sms</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>From</th>
      <th>Received at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sms.each do |sm| %>
      <tr>
        <td><%= sm.body %></td>
        <td><%= sm.from %></td>
        <td><%= sm.received_at %></td>
        <td><%= link_to 'Show', sm %></td>
        <td><%= link_to 'Edit', edit_sm_path(sm) %></td>
        <td><%= link_to 'Destroy', sm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sm', new_sm_path %>

app/views/sms/new.html.erb
<h1>New Sm</h1>

<%= render 'form', sm: @sm %>

<%= link_to 'Back', sms_path %>

app/views/sms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @sm.body %>
</p>

<p>
  <strong>From:</strong>
  <%= @sm.from %>
</p>

<p>
  <strong>Received at:</strong>
  <%= @sm.received_at %>
</p>

<%= link_to 'Edit', edit_sm_path(@sm) %> |
<%= link_to 'Back', sms_path %>